project:
  type: website
  execute-dir: project
  render: # Add HERE new chapters (but not the interactive qmd files)
    - index.qmd
    - chapters/chapter1.qmd
    - chapters/chapter2.qmd

website:
  page-navigation: true
  title: "Early Imputation Use Case"
  site-url: "https://github.com/AIML4OS/WP9_S1_PL_TOURISM"
  repo-url: "https://github.com/AIML4OS/WP9_S1_PL_TOURISM"
  repo-actions: [edit, source, issue]
  # favicon: images/Template2.png
  sidebar:
    logo: resources/profile/main3.png
    style: "docked"
    search: true
    contents: # Add HERE new chapters (but not the interactive qmd files)
      - href: index.qmd
        text: Introduction
      - href: chapters/chapter1.qmd
        text: Explanatory Data Analysis
      - href: chapters/chapter2.qmd
        text: Feature Engineering
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

filters:
  - export-metadata.lua

